services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5076:5076"
    environment:
      - ASPNETCORE_URLS=http://+:5076
      - DB_HOST=db
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - JWT_KEY=${JWT_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_EXPIRATION_HOURS=${JWT_EXPIRATION_HOURS}
      - MAIL_SMTP_SERVER=${MAIL_SMTP_SERVER}
      - MAIL_SMTP_PORT=${MAIL_SMTP_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - APP_PASSWORD=${APP_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: